/** Render fixture YAML without importing the Playwright test lifecycle. */
export function mockProviderConfig(
  mockUrl: string,
  extraDisplayConfig?: string,
  extraConfig?: string,
  modelContextLength?: number,
  modelStreaming?: boolean
): string {
  const displaySection = extraDisplayConfig ? `\ndisplay:\n${extraDisplayConfig}\n` : ''

  // Title generation rides the MAIN model since 87af576e60 (#83636), so every
  // completed turn fires an extra background /v1/chat/completions at the mock.
  // That request contains the whole conversation — trigger keywords included —
  // which advances the mock's scripted-turn indices and trips hold-for-prompt
  // matchers from a request no spec ever sent. Disable it by default (no e2e
  // spec asserts on session titles); a test that passes its own `auxiliary:`
  // section via extraConfig owns the whole section instead.
  const autoTitleDefault = extraConfig?.includes('auxiliary:')
    ? ''
    : 'auxiliary:\n  title_generation:\n    enabled: false\n'

  // The scripted turns run REAL terminal commands, and anything the guard
  // classifies as dangerous (e.g. the sidebar sentinel-wait loop) parks the
  // turn behind a Run/Reject approval card. The default 'smart' mode then
  // fires an aux LLM approval call at the SAME mock provider — consuming a
  // scripted-turn index and never resolving — so the turn stalls until the
  // spec times out (the CI failure mode for the sidebar-dot family). No e2e
  // spec asserts on the approval flow, so run gate-free by default; a test
  // that passes its own `approvals:` section via extraConfig owns it.
  const approvalsDefault = extraConfig?.includes('approvals:') ? '' : 'approvals:\n  mode: "off"\n'

  return `# Auto-generated by E2E test fixtures
model:
  default: mock-model
  provider: mock
${modelContextLength ? `  context_length: ${modelContextLength}\n` : ''}${typeof modelStreaming === 'boolean' ? `  streaming: ${modelStreaming}\n` : ''}providers:
  mock:
    api: ${mockUrl}/v1
    name: Mock
    api_mode: chat_completions
    key_env: MOCK_API_KEY
    models:
      mock-model: {}
    context_length: ${modelContextLength ?? 4096}
${autoTitleDefault}${approvalsDefault}${displaySection}${extraConfig ? `\n${extraConfig.trim()}\n` : ''}`
}
