import { describe, expect, it } from 'vitest'

import { createPrototypeAdapter } from '../../../test-fixtures/organization-prototype'

describe('prototype organization objective lifecycle', () => {
  it.each(['{not-json', 'null', '{}'])('recovers unreadable persisted data %s without overwriting it', saved => {
    let writes = 0
    const adapter = createPrototypeAdapter({ getItem: () => saved, setItem: () => { writes++ } })
    expect(adapter.getSnapshot().objectives).toEqual([])
    expect(writes).toBe(0)
    adapter.reset()
    expect(writes).toBe(1)
  })
  it('retains an explicitly user-recorded outcome as knowledge without claiming execution', () => {
    const adapter = createPrototypeAdapter()
    const objective = adapter.createObjective('Document the workflow')
    expect(() => adapter.recordOutcome(objective.id, ' ')).toThrow()
    adapter.recordOutcome(objective.id, 'Reviewed the draft with the team.')
    const snapshot = adapter.getSnapshot()
    expect(snapshot.objectives[0].status).toBe('completed')
    expect(snapshot.objectives[0].result).toBe('Reviewed the draft with the team.')
    expect(snapshot.knowledge[0].objectiveId).toBe(objective.id)
    expect(snapshot.knowledge[0].body).toContain('User-recorded')
    expect(snapshot.tasks.every(task => task.status === 'queued')).toBe(true)
    expect(snapshot.activity[0].text).toContain('No live execution')
  })
  it('records local approval without dispatching work', () => {
    const adapter = createPrototypeAdapter()
    adapter.loadDemo()
    const decision = adapter.getSnapshot().decisions?.find(item => item.status === 'pending')
    expect(decision).toBeDefined()
    adapter.resolveDecision(decision!.id, 'approved')
    expect(adapter.getSnapshot().decisions?.find(item => item.id === decision!.id)?.status).toBe('approved')
    expect(adapter.getSnapshot().activity[0].text).toContain('local prototype')
  })
  it('keeps user-created relationships intact when loading the example repeatedly', () => {
    const adapter = createPrototypeAdapter()
    const objective = adapter.createObjective('Plan a delivery')
    adapter.loadDemo()
    adapter.loadDemo()
    const snapshot = adapter.getSnapshot()
    expect(snapshot.tasks.filter(task => task.objectiveId === objective.id)).toHaveLength(3)
    expect(snapshot.tasks.every(task => snapshot.agents.some(agent => agent.id === task.ownerId))).toBe(true)
    expect(new Set(snapshot.agents.map(agent => agent.id)).size).toBe(snapshot.agents.length)
  })
  it('loads only explicitly requested example data and can clear it', () => {
    const adapter = createPrototypeAdapter()
    expect(adapter.getSnapshot().agents).toHaveLength(0)
    adapter.loadDemo()
    expect(adapter.getSnapshot().agents.length).toBeGreaterThan(0)
    expect(adapter.getSnapshot().tasks.length).toBeGreaterThan(0)
    adapter.reset()
    expect(adapter.getSnapshot().objectives).toHaveLength(0)
  })
  it('keeps a submitted goal in local planning without inventing live work', () => {
    const adapter = createPrototypeAdapter()
    expect(() => adapter.createObjective('   ')).toThrow('Describe')
    const objective = adapter.createObjective('  Prepare launch notes  ')
    expect(objective.title).toBe('Prepare launch notes')
    expect(objective.status).toBe('planning')
    expect(objective.source).toBe('prototype')
    expect(objective.sessionId).toBeUndefined()
    expect(adapter.getSnapshot().objectives).toContainEqual(objective)
    const created = adapter.getSnapshot()
    expect(created.tasks.filter(task => task.objectiveId === objective.id)).toHaveLength(3)
    expect(created.activity.filter(event => event.objectiveId === objective.id).length).toBeGreaterThan(2)
    expect(created.tasks.every(task => created.agents.some(agent => agent.id === task.ownerId))).toBe(true)
    expect(created.agents.every(agent => agent.profileName === undefined)).toBe(true)
    adapter.setObjectiveStatus(objective.id, 'paused')
    expect(adapter.getSnapshot().objectives.find(item => item.id === objective.id)?.status).toBe('paused')
    expect(adapter.getSnapshot().activity[0].source).toBe('prototype')
    expect(adapter.getSnapshot().activity[0].objectiveId).toBe(objective.id)
  })
})
