name: 'Setup Nix'
description: 'Install Nix without an upstream project cache connection'


runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
